apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogInByb21ldGhldXMiCiAgc3RhdGljX2NvbmZpZ3M6CiAgLSB0YXJnZXRzOiBbIjEwLjQzLjAuNTA6OTYxNyJdCiAgLSB0YXJnZXRzOiBbIjEwLjQzLjAuNTE6OTYxNyJdCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
