apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  namespace: pihole-2
  labels:
    app: pihole-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pihole-2
  template:
    metadata:
      labels:
        app: pihole-2
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: az
          whenUnsatisfiable: DoNotSchedule
      containers:
      - name: pihole
        image: pihole/pihole
        envFrom:
        - configMapRef:
            name: pihole-network-env
        - configMapRef:
            name: pihole-env
        ports:
        - name: web
          containerPort: 80
        - name : dns
          protocol : UDP
          containerPort: 53
        volumeMounts:
        - name: pihole-adlists
          mountPath: /etc/pihole/adlists.list
          subPath: adlists.list
        - name: pihole-regex
          mountPath: /etc/pihole/regex.list
          subPath: regex.list
        - name: pihole-custom
          mountPath: /etc/pihole/custom.list
          subPath: custom.list
      volumes:
        - name: pihole-adlists
          configMap:
            name: pihole-adlists
        - name: pihole-regex
          configMap: 
            name: pihole-regex
        - name: pihole-custom
          configMap: 
            name: pihole-custom