kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: pihole
  name: pvc-pihole-2
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-2-configmap
  namespace: pihole
data:
  TZ: "America/Los Angeles"
  ADMIN_EMAIL: "<n+pihole@aux.sh>"
  DNS1: "10.43.0.20"
  DNS2: "10.43.0.20"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole-2
  namespace: pihole
  labels:
    app: pihole-2
spec:
  serviceName: "pihole-2"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pihole-2
  template:
    metadata:
      labels:
        app: pihole-2
    spec:
      containers:
      - name: pihole-2
        image: docker.io/pihole/pihole:latest
        envFrom:
        - configMapRef:
            name: pihole-2-configmap 
        ports:
        - name: svc-53-udp
          containerPort: 53
          protocol: UDP
        - name: svc-53-tcp
          containerPort: 53
          protocol: TCP
        - name: svc-ui-http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: "2000Mi"
            cpu: "1000m"
          requests:
            memory: "1000Mi"
            cpu: "1000m"
        volumeMounts:
        - mountPath: /etc/pihole
          name: pihole-2-etc
      volumes:
        - name: pihole-2-etc
          persistentVolumeClaim:
            claimName: pvc-pihole-2
---
kind: Service 
apiVersion: v1 
metadata:
  name: pihole-2-ui-svc
  namespace: pihole
spec:
  selector:
    app: pihole-2
  type: ClusterIP
  ports:
    - name: 80-tcp
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-2-web-tcp
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-2-svc
spec:
  selector:
    app: pihole-2
  ports:
    - name: 80-tcp
      port: 80
      targetPort: 80
      protocol: TCP
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.1.30
---
kind: Service 
apiVersion: v1 
metadata:
  name: pihole-2-dns-svc 
  namespace: pihole
spec:
  selector:
    app: pihole-2
  type: ClusterIP
  clusterIP: 10.43.0.40
  ports:
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-2-dns-udp
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-2-svc
spec:
  selector:
    app: pihole-2
  ports:
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.1.30
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-2-dns-tcp
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-2-svc
spec:
  selector:
    app: pihole-2
  ports:
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.1.30
